Controllers/SourceController.cs
using CIAT.DAPA.USAID.Forecast.Data.Enums;
using CIAT.DAPA.USAID.Forecast.Data.Models;
using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Tools;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CIAT.DAPA.USAID.Forecast.WebAdmin.Controllers
{
    [Authorize(Roles = "ADMIN,CLIMATOLOGIST,IMPROVER")]
    [Authorize]
    public class SourceController : WebAdminBaseController
    {
        /// <summary>
        /// Method Construct
        /// </summary>
        /// <param name="settings">Settings options</param>
        /// <param name="hostingEnvironment">Host Enviroment</param>
        public SourceController(IOptions<Settings> settings, IHostingEnvironment hostingEnvironment,
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            RoleManager<Role> roleManager, IEmailSender emailSender) : 
            base(settings, LogEntity.ad_source, hostingEnvironment, userManager, signInManager, roleManager, emailSender)
        {
        }

        // GET: /Source/
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var list = await db.source.listEnableAsync();
                await writeEventAsync(list.Count().ToString(), LogEvent.lis);
                return View(list);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return View();
            }

        }

        // GET: /Source/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    await writeEventAsync("Search without id", LogEvent.err);
                    return new BadRequestResult();
                }
                Source entity = await db.source.byIdAsync(id);
                if (entity == null)
                {
                    await writeEventAsync("Not found id: " + id, LogEvent.err);
                    return new NotFoundResult();
                }
                await writeEventAsync("Search id: " + id, LogEvent.rea);
                return View(entity);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return View();
            }
        }

        // GET: /Source/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: /Source/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Source entity)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await db.source.insertAsync(entity);
                    await writeEventAsync(entity.ToString(), LogEvent.cre);
                    return RedirectToAction("Index");
                }
                await writeEventAsync(ModelState.ToString(), LogEvent.err);
                return View(entity);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return View(entity);
            }
        }

        // GET: /Source/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    await writeEventAsync("Search without id", LogEvent.err);
                    return new BadRequestResult();
                }
                Source entity = await db.source.byIdAsync(id);
                if (entity == null)
                {
                    await writeEventAsync("Not found id: " + id, LogEvent.err);
                    return new NotFoundResult();
                }
                await writeEventAsync("Search id: " + id, LogEvent.rea);
                return View(entity);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return View();
            }
        }

        // POST: /Source/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Source entity, string id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Source current_entity = await db.source.byIdAsync(id);

                    entity.id = getId(id);
                    await db.source.updateAsync(current_entity, entity);
                    await writeEventAsync(entity.ToString(), LogEvent.upd);
                    return RedirectToAction("Index");
                }
                await writeEventAsync(ModelState.ToString(), LogEvent.err);
                return View(entity);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return View(entity);
            }
        }

        // GET: /Source/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    await writeEventAsync("Search without id", LogEvent.err);
                    return new BadRequestResult();
                }
                Source entity = await db.source.byIdAsync(id);
                if (entity == null)
                {
                    await writeEventAsync("Not found id: " + id, LogEvent.err);
                    return new NotFoundResult();
                }
                await writeEventAsync("Search id: " + id, LogEvent.rea);
                return View(entity);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return View();
            }
        }

        // POST: /Source/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            try
            {
                Source entity = await db.source.byIdAsync(id);
                await db.source.deleteAsync(entity);
                await writeEventAsync(entity.ToString(), LogEvent.del);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return RedirectToAction("Delete", new { id = id });
            }
        }
    }
}

Controllers/UrlController.cs
using CIAT.DAPA.USAID.Forecast.Data.Enums;
using CIAT.DAPA.USAID.Forecast.Data.Models;
using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Tools;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CIAT.DAPA.USAID.Forecast.WebAdmin.Controllers
{
    [Authorize(Roles = "ADMIN,IMPROVER")]
    [Authorize]
    public class UrlController : WebAdminBaseController
    {
        /// <summary>
        /// Method Construct
        /// </summary>
        /// <param name="settings">Settings options</param>
        /// <param name="hostingEnvironment">Host Enviroment</param>
        public UrlController(IOptions<Settings> settings, IHostingEnvironment hostingEnvironment,
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            RoleManager<Role> roleManager, IEmailSender emailSender) :
            base(settings, LogEntity.cp_url, hostingEnvironment, userManager, signInManager, roleManager, emailSender)
        {
        }

        private async Task<PermissionList> LoadEnableByPermissionAsync(string countrySelected = "")
        {
            UserPermission permission = await getPermissionAsync();
            PermissionList val = new PermissionList();
            val.countries = await db.country.listEnableAsync();
            val.countries = val.countries.Where(p => permission.countries.Contains(p.id)).ToList();
            val.urls = await db.url.listAsync();
            if (countrySelected != "" && countrySelected != "000000" && permission.countries.Count() > 1)
            {
                val.urls = val.urls.Where(p => permission.countries.Contains(p.country) && p.country == new MongoDB.Bson.ObjectId(countrySelected)).ToList();
            }
            else if (countrySelected == "" && permission.countries.Count() > 1)
            {
                val.urls = val.urls.Where(p => permission.countries.Contains(p.country) && p.country == permission.countries.FirstOrDefault()).ToList();
            }
            else
            {
                val.urls = val.urls.Where(p => permission.countries.Contains(p.country)).ToList();
            }
            return val;
        }

        // GET: /Url/
        [HttpGet]
        public async Task<IActionResult> Index(string countrySelect = "")
        {
            try
            {
                PermissionList obj = await LoadEnableByPermissionAsync(countrySelect);
                List<Url> list = obj.urls;
                ViewBag.countries = obj.countries;


                if (countrySelect == "")
                {
                    ViewBag.countrySelected = obj.countries[0].id.ToString();
                }
                else
                {
                    ViewBag.countrySelected = "";
                }
                ViewData["countriesData"] = getCountriesListWithDefult(obj, countrySelect);
                string dataJson = JsonConvert.SerializeObject(getListOfCountryUrl(obj));
                ViewBag.data = dataJson;

                await writeEventAsync(list.Count().ToString(), LogEvent.lis);
                return View(list);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return View();
            }

        }

        // GET: /Url/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    await writeEventAsync("Search without id", LogEvent.err);
                    return new BadRequestResult();
                }
                Url entity = await db.url.byIdAsync(id);
                ViewBag.country = await db.country.byIdAsync(entity.country.ToString());
                if (entity == null)
                {
                    await writeEventAsync("Not found id: " + id, LogEvent.err);
                    return new NotFoundResult();
                }
                await writeEventAsync("Search id: " + id, LogEvent.rea);
                return View(entity);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return View();
            }
        }

        // GET: /Url/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await generateListCountriesAsync("");
            await generateListTypeAsync();
            return View();
        }


        // POST: /Url/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateUrl()
        {
            try
            {
                var form = HttpContext.Request.Form;
                int count = form.Keys.Where(p => p.Contains("url_name_")).Count();
                List<UrlData> url_data = new List<UrlData>();
                string country_id = form["country"];
                for (int i = 1; i <= count; i++)
                {
                    url_data.Add(new UrlData()
                    {
                        name = form["url_name_" + i.ToString()],
                        value = form["url_value_" + i.ToString()],
                        forc_type = (ForecastType)int.Parse(form["forc_type_" + i.ToString()]),
                        prob_type = (CategoryUrl)int.Parse(form["prob_type_" + i.ToString()]),

                    });
                }
                if (url_data.Count() == 0)
                    return RedirectToAction("Create");
                Url entity = new Url()
                {
                    country = MongoDB.Bson.ObjectId.Parse(country_id),
                    type = (UrlTypes)int.Parse(form["type"]),
                    urls = url_data
                };
                await db.url.insertAsync(entity);
                await writeEventAsync(ModelState.ToString(), LogEvent.err);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return RedirectToAction("Create");
            }
        }

        // GET: /Url/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    await writeEventAsync("Search without id", LogEvent.err);
                    return new BadRequestResult();
                }
                Url entity = await db.url.byIdAsync(id);
                if (entity == null)
                {
                    await writeEventAsync("Not found id: " + id, LogEvent.err);
                    return new NotFoundResult();
                }
                await generateListCountriesAsync(entity.country.ToString());
                await generateListTypeAsync();
                await writeEventAsync("Search id: " + id, LogEvent.rea);
                return View(entity);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return View();
            }
        }

        // POST: /Url/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUrl()
        {
            try
            {
                var form = HttpContext.Request.Form;
                Url current_entity = await db.url.byIdAsync(form["id"]);

                int count = form.Keys.Where(p => p.Contains("url_name_")).Count();
                List<UrlData> url_data = new List<UrlData>();
                string country_id = form["country"];
                for (int i = 1; i <= count; i++)
                {
                    url_data.Add(new UrlData()
                    {
                        name = form["url_name_" + i.ToString()],
                        value = form["url_value_" + i.ToString()],
                        forc_type = (ForecastType)int.Parse(form["forc_type_" + i.ToString()]),
                        prob_type = (CategoryUrl)int.Parse(form["prob_type_" + i.ToString()]),

                    });
                }
                if (url_data.Count() == 0)
                    return RedirectToAction("Edit", new RouteValueDictionary { { "id", current_entity.id } });
                Url entity = new Url()
                {
                    id = current_entity.id,
                    country = MongoDB.Bson.ObjectId.Parse(country_id),
                    type = (UrlTypes)int.Parse(form["type"]),
                    urls = url_data
                };
                await db.url.updateAsync(current_entity, entity);
                await writeEventAsync(entity.ToString(), LogEvent.upd);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                var form = HttpContext.Request.Form;
                await generateListCountriesAsync(form["id"]);
                Url current_entity = await db.url.byIdAsync(form["id"]);
                await writeExceptionAsync(ex);
                return RedirectToAction("Edit", new RouteValueDictionary { { "id", current_entity.id } });
            }
        }

        // GET: /Url/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    await writeEventAsync("Search without id", LogEvent.err);
                    return new BadRequestResult();
                }
                Url entity = await db.url.byIdAsync(id);
                if (entity == null)
                {

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">@Localizer["MenuMain"]</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown text-bold">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span> @Localizer["MenuAdmin"]<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            @if (User.IsInRole("ADMIN") || User.IsInRole("CLIMATOLOGIST") || User.IsInRole("IMPROVER"))
                            {
                                <li><a asp-area="" asp-controller="Source" asp-action="Index">@Localizer["MenuSources"]</a></li>
                            }
                            @if (User.IsInRole("ADMIN") || User.IsInRole("TECH"))
                            {
                                <li><a asp-area="" asp-controller="Account" asp-action="Index">@Localizer["MenuUsers"]</a></li>
                            }

                        </ul>
                    </li>
                    @if (User.IsInRole("ADMIN") || User.IsInRole("CLIMATOLOGIST"))
                    {
                        <li class="dropdown text-bold">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-globe"></span> @Localizer["MenuGeography"]<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Country" asp-action="Index">@Localizer["MenuCountry"]</a></li>
                                <li><a asp-area="" asp-controller="State" asp-action="Index">@Localizer["MenuStates"]</a></li>
                                <li><a asp-area="" asp-controller="Municipality" asp-action="Index">@Localizer["MenuMunicipalities"]</a></li>
                                <li><a asp-area="" asp-controller="WeatherStation" asp-action="Index">@Localizer["MenuWS"]</a></li>
                            </ul>
                        </li>
                    }
                    @if (User.IsInRole("ADMIN") || User.IsInRole("IMPROVER"))
                    {
                        <li class="dropdown text-bold">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-grain"></span> @Localizer["MenuProduction"]<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Crop" asp-action="Index">@Localizer["MenuCrops"]</a></li>
                                <li><a asp-area="" asp-controller="Cultivar" asp-action="Index">@Localizer["MenuCultivars"]</a></li>
                                <li><a asp-area="" asp-controller="Soil" asp-action="Index">@Localizer["MenuSoils"]</a></li>
                                <li><a asp-area="" asp-controller="Setup" asp-action="Index">@Localizer["MenuSetups"]</a></li>
                                <li><a asp-area="" asp-controller="Recommendation" asp-action="Index">@Localizer["MenuRecommendation"]</a></li>
                                <li><a asp-area="" asp-controller="Url" asp-action="Index">@Localizer["MenuUrl"]</a></li>
                            </ul>
                        </li>
                    }
                    @if (User.IsInRole("ADMIN") || User.IsInRole("CLIMATOLOGIST") || User.IsInRole("IMPROVER"))
                    {
                        <li class="dropdown text-bold">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-cloud-upload"></span> @Localizer["MenuImport"]<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Import" asp-action="HistoricalClimate">@Localizer["MenuHistoricalClimatic"]</a></li>
                                <li><a asp-controller="Import" asp-action="Climatology">@Localizer["MenuClimatology"]</a></li>
                                <li><a asp-controller="Import" asp-action="HistoricalYield">@Localizer["MenuHistoricalYield"]</a></li>
                            </ul>
                        </li>
                    }
                    </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>@Localizer["Footer"]</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_ManagementScriptsPartial.cshtml
<script>
    function search_text() {
        // Declare variables
        var input, filter, table, tr, td, i, txtValue, found;
        input = document.getElementById("txt_search");
        filter = input.value.toUpperCase();
        table = document.getElementById("index_list");
        tr = table.getElementsByTagName("tr");

        // Loop through all table rows, and hide those who don't match the search query
        for (i = 1; i < tr.length; i++) {
            tds = tr[i].getElementsByTagName("td");
            found = false;
            for (j = 0; j < tds.length - 1; j++) {
                td = tds[j];
                if (td) {
                    txtValue = td.textContent || td.innerText;

                    found = txtValue.toUpperCase().indexOf(filter) > -1;
                    if (found) break;
                }
            }
            tr[i].style.display = found ? "" : "none";
        }
    }



    /*function change_filter(selectedValue, urlModule) {
        // Declare variables
        let tableF, trF, tdF, i, txtValue, found, filterData, selectElement;
        tableF = document.getElementById("index_list");
        trF = tableF.getElementsByTagName("tr");
        selectElement = document.getElementById("countrySelect");
        document.getElementById("txt_search").value = ""

        $(document).ready(function () {
            selectElement.disabled = true;
            $.ajax({
                url: `/${urlModule}/ObtainCountryFilterData`, // Ruta de la acción en el controlador que devuelve los datos
                type: 'GET',
                success: function (listData) {
                    selectElement.disabled = false;
                    filterData = listData.find(st => st.countryId == selectedValue)?.listData;
                    data = filterData
                    // Loop through all table rows, and hide those who don't match the search query
                    for (i = 1; i < trF.length; i++) {
                        tds = trF[i].getElementsByTagName("td");
                        if (selectedValue == "000000") {
                            trF[i].style.display = "";
                            data = []
                        } else {
                            found = false;
                            for (j = 0; j < tds.length - 1; j++) {
                                tdF = tds[j];
                                if (tdF) {
                                    txtValue = tdF.innerText.replaceAll("\n", "").replaceAll(" ", "");
                                    found = filterData.find(p => p.id == txtValue) != undefined;
                                    if (found)
                                        break;
                                }
                            }
                            trF[i].style.display = found ? "" : "none";
                        }

                    }
                }
            });
        });

        

    }*/
    function submitForm() {
        let form = document.getElementById("selectForm");

        form.submit();
    }
    $(document).ready(function () {
        let selected = document.getElementById("countrySelected")
        let select = document.getElementById("countrySelect")
        if (selected && select) {
            let options = select.getElementsByTagName("option")
            for (i = 0; i < options.length; i++) {
                if (options[i].value == selected.value) {
                    options[i].selected = true
                }
            }
        }




    })
    
</script>

Views/Shared/_PyCPTList.cshtml
@model (string id, IEnumerable<CIAT.DAPA.USAID.Forecast.Data.Models.ConfigurationPyCPT> conf, string[] months, string controller, string action_delete)

<h3>@Localizer["SetupAvalaible"]</h3>
<table class="table">
    <tr>
        <th>@Localizer["Date"]</th>
        <th>@Localizer["Month"]</th>
        <th>@Localizer["Obs"]</th>
        <th>@Localizer["Mos"]</th>
        <th>@Localizer["Models"]</th>
        <th>@Localizer["Predictand"]</th>
        <th>@Localizer["Predictors"]</th>
        <th>@Localizer["Ranges"]</th>
        <th>@Localizer["OthersParameters"]</th>
        <th></th>
    </tr>
    @if (Model.conf != null)
    {
        @foreach (var item in Model.conf.Where(p => p.track.enable).OrderBy(p => p.track.register).OrderBy(p => p.month))
        {
            <tr>
                <td>@item.track.register.ToString("yyyy-MM-dd")</td>
                <td>@Model.months[item.month - 1]</td>
                <td>@item.obs</td>
                <td>@item.mos</td>
                <td>
                    <ul>
                        @foreach (var i in item.models)
                        {
                            <li>@i</li>
                        }
                    </ul>
                </td>
                <td>
                    @item.predictors
                    <br />
                    <b>N: </b>@item.spatial_predictors.rigth_upper.lat
                    <br />
                    <b>S: </b>@item.spatial_predictors.left_lower.lat
                    <br />
                    <b>E: </b>@item.spatial_predictors.rigth_upper.lon
                    <br />
                    <b>W: </b>@item.spatial_predictors.left_lower.lon
                    <br />
                </td>
                <td>
                    @item.predictand
                    <br />
                    <b>N: </b>@item.spatial_predictands.rigth_upper.lat
                    <br />
                    <b>S: </b>@item.spatial_predictands.left_lower.lat
                    <br />
                    <b>E: </b>@item.spatial_predictands.rigth_upper.lon
                    <br />
                    <b>W: </b>@item.spatial_predictands.left_lower.lon
                    <br />
                </td>

                <td>
                    <ul>
                        <li><b>@Localizer["Years"]:</b> [@item.ranges_years.min - @item.ranges_years.max]</li>
                        <li><b>@Localizer["CCAModes"]:</b> [@item.ccamodes.min - @item.ccamodes.max]</li>
                        <li><b>@Localizer["XModes"]:</b> [@item.xmodes.min - @item.xmodes.max]</li>
                        <li><b>@Localizer["YModes"]:</b> [@item.ymodes.min - @item.ymodes.max]</li>
                    </ul>
                </td>
                <td>
                    <ul>
                        <li><b>@Localizer["Station"]:</b> @item.station</li>
                        <li><b>@Localizer["SingleModels"]:</b> @item.single_models</li>
                        <li><b>@Localizer["ForecastAnomaly"]:</b> @item.forecast_anomaly</li>
                        <li><b>@Localizer["ForecastSpi"]:</b> @item.forecast_spi</li>
                        <li><b>@Localizer["ConfidenceLevel"]:</b> @item.confidence_level</li>
                    </ul>
                </td>
                <td>
                    @using (Html.BeginForm(Model.action_delete, Model.controller, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <input type="hidden" id="id" name="id" value="@Model.id" />
                        <input type="hidden" id="month" name="month" value="@item.month" />
                        <input type="hidden" id="register" name="register" value="@item.track.register.Ticks.ToString()" />
                        <input class="btn btn-danger" type="submit" value="@Localizer["Delete"]" />
                    }
                </td>
            </tr>
        }
    }
</table>