Models/Import/ClimatologyViewImport.cs
using CIAT.DAPA.USAID.Forecast.Data.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Import
{
    /// <summary>
    /// This class is a view import of the climatology
    /// </summary>
    public class ClimatologyViewImport
    {
        /// <summary>
        /// Type of measure
        /// </summary>
        public MeasureClimatic measure { get; set; }
        /// <summary>
        /// Month of the historical data
        /// </summary>
        public int month { get; set; }
        /// <summary>
        /// Extern id of the weather station
        /// </summary>
        public string ext_id { get; set; }
        /// <summary>
        /// Name of the weather station
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// Value of the climate data
        /// </summary>
        public double value { get; set; }
    }
}

Models/Import/HistoricalClimateViewImport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Import
{
    /// <summary>
    /// This class is a view of the importer
    /// </summary>
    public class HistoricalClimateViewImport
    {
        /// <summary>
        /// Year of the historical data
        /// </summary>
        public int year { get; set; }
        /// <summary>
        /// Month of the historical data
        /// </summary>
        public int month { get; set; }
        /// <summary>
        /// Extern id of the weather station
        /// </summary>
        public string ext_id { get; set; }
        /// <summary>
        /// Name of the weather station
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// Value of the climate data
        /// </summary>
        public double value { get; set; }
    }
}

Models/Import/HistoricalYieldViewImport.cs
using CIAT.DAPA.USAID.Forecast.Data.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Import
{
    /// <summary>
    /// This class is a view of the importer
    /// </summary>
    public class HistoricalYieldViewImport
    {
        /// <summary>
        /// Id of the weather station
        /// </summary>
        public string weather_station { get; set; }
        /// <summary>
        /// Id of the soil
        /// </summary>
        public string soil { get; set; }
        /// <summary>
        /// Id of the cultivar
        /// </summary>
        public string cultivar { get; set; }
        /// <summary>
        /// Start date
        /// </summary>
        public DateTime start { get; set; }
        /// <summary>
        /// End date
        /// </summary>
        public DateTime end { get; set; }
        /// <summary>
        /// Measure yield
        /// </summary>
        public MeasureYield measure { get; set; }
        /// <summary>
        /// Median
        /// </summary>
        public double median { get; set; }
        /// <summary>
        /// Average
        /// </summary>
        public double avg { get; set; }
        /// <summary>
        /// Minimun value
        /// </summary>
        public double min { get; set; }
        /// <summary>
        /// Maximun value
        /// </summary>
        public double max { get; set; }
        /// <summary>
        /// First quartile
        /// </summary>
        public double quar_1 { get; set; }
        /// <summary>
        /// Second quartile
        /// </summary>
        public double quar_2 { get; set; }
        /// <summary>
        /// Third quartile
        /// </summary>
        public double quar_3 { get; set; }
        /// <summary>
        /// Limit lower confidence
        /// </summary>
        public double conf_lower { get; set; }
        /// <summary>
        /// Limit upper confidence
        /// </summary>
        public double conf_upper { get; set; }
        /// <summary>
        /// Standard desviation
        /// </summary>
        public double sd { get; set; }
        /// <summary>
        /// 5 percentile
        /// </summary>
        public double perc_5 { get; set; }
        /// <summary>
        /// 95 percentile
        /// </summary>
        public double perc_95 { get; set; }
        /// <summary>
        /// coefficient of variation
        /// </summary>
        public double coef_var { get; set; }
    }
}

Controllers/ImportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Tools;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using CIAT.DAPA.USAID.Forecast.Data.Enums;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using CIAT.DAPA.USAID.Forecast.Data.Models;
using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Import;
using System.IO;
using System.Globalization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace CIAT.DAPA.USAID.Forecast.WebAdmin.Controllers
{
    [Authorize(Roles = "ADMIN,CLIMATOLOGIST,IMPROVER")]
    [Authorize]
    public class ImportController : WebAdminBaseController
    {
        /// <summary>
        /// Method Construct
        /// </summary>
        /// <param name="settings">Settings options</param>
        /// <param name="hostingEnvironment">Host Enviroment</param>
        public ImportController(IOptions<Settings> settings, IHostingEnvironment hostingEnvironment,
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            RoleManager<Role> roleManager, IEmailSender emailSender) :
            base(settings, LogEntity.lc_weather_station, hostingEnvironment, userManager, signInManager, roleManager, emailSender)
        {
        }

        // GET: /Import/ImportHistoricalClimate
        [HttpGet]
        public async Task<IActionResult> HistoricalClimate()
        {
            try
            {
                // List climate variables
                await generateListMeasuresAndSourceAsync();

                return View();
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: /Import/ImportHistoricalClimate
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> HistoricalClimate(int search, int measures, IFormFile file)
        {
            Message msg = null;
            try
            {
                if (file != null && file.Length > 0)
                {
                    // Save a copy in the web site
                    await file.CopyToAsync(new FileStream(importPath + DateTime.Now.ToString("yyyyMMddHHmmss") + "-weatherstation-historical-climate-ws-" + file.FileName, FileMode.Create));
                    // Read the file
                    StreamReader reader = new StreamReader(file.OpenReadStream());
                    string line = string.Empty;
                    int lines = 0;
                    IEnumerable<WeatherStation> ws = null;
                    List<HistoricalClimateViewImport> raw = new List<HistoricalClimateViewImport>();
                    string[] patterns = null;
                    string[] values = null;
                    // Read the file
                    while (!reader.EndOfStream)
                    {
                        line = await reader.ReadLineAsync();
                        if (!string.IsNullOrEmpty(line))
                        {
                            lines += 1;
                            // Reading the headers
                            if (lines == 1)
                            {
                                patterns = line.Replace("\"", "").Split(',').Skip(2).ToArray();
                                // Searching the weather stations according of the parameter to seek
                                if (search == 1)
                                    ws = await db.weatherStation.listEnableByExtIDsAsync(patterns);
                                else if (search == 2)
                                    ws = await db.weatherStation.listEnableByNamesAsync(patterns);
                            }
                            else
                            {
                                // Fixed the values to view import historical climate
                                // The first two columns are the year and month
                                values = line.Split(',');
                                for (int i = 2; i < values.Length; i++)
                                    raw.Add(new HistoricalClimateViewImport()
                                    {
                                        year = int.Parse(values[0]),
                                        month = int.Parse(values[1]),
                                        ext_id = search == 1 ? patterns[i - 2] : string.Empty,
                                        name = search == 2 ? patterns[i - 2] : string.Empty,
                                        value = double.Parse(values[i], CultureInfo.InvariantCulture)
                                    });
                            }
                        }
                    }
                    // Import to the database
                    WeatherStation ws_entity;
                    HistoricalClimatic hc_entity, hc_new;
                    MeasureClimatic mc = (MeasureClimatic)measures;
                    List<ClimaticData> data;
                    // In this section it is filtered the data of the field loaded and the historical information is added to the data base.
                    // We first get the ids of the climate stations, then it is filtered the information of each year and each station. 
                    // With this information we look for in the data base if it historical information stored, in case that it is not created in 
                    // a new identity. It is filtered the information of every month in order to add the data to the field.
                    // At the end it is updated the information. If there is not a file, it is created as a new one.
                    var ws_patterns = search == 1 ? raw.Select(p => p.ext_id).Distinct() : raw.Select(p => p.name).Distinct();
                    foreach (var y in raw.Select(p => p.year).Distinct())
                    {
                        foreach (var ws_p in ws_patterns)
                        {
                            var ws_values = search == 1 ? raw.Where(p => p.ext_id == ws_p && p.year == y) : raw.Where(p => p.name == ws_p && p.year == y);
                            ws_entity = search == 1 ? ws.FirstOrDefault(p => p.ext_id == ws_p) : ws.FirstOrDefault(p => p.name == ws_p);
                            if (ws_entity != null)
                            {
                                hc_entity = await db.historicalClimatic.byYearWeatherStationAsync(y, ws_entity.id);
                                if (hc_entity == null)
                                    hc_new = new HistoricalClimatic() { weather_station = ws_entity.id, year = y, monthly_data = new List<MonthlyDataStation>() };
                                else
                                    hc_new = new HistoricalClimatic() { id = hc_entity.id, weather_station = hc_entity.weather_station, year = y, monthly_data = hc_entity.monthly_data };
                                var months = ws_values.Select(p => p.month);
                                foreach (var m in months)
                                {
                                    var monthlyData = hc_new.monthly_data.FirstOrDefault(p => p.month == m) ?? new MonthlyDataStation() { month = m, data = new List<ClimaticData>() };
                                    var restMonthlyData = hc_new.monthly_data.Where(p => p.month != m).ToList() ?? new List<MonthlyDataStation>();
                                    data = monthlyData.data.ToList();
                                    data.Add(ws_values.Where(p => p.month == m).Select(p => new ClimaticData() { measure = mc, value = p.value }).FirstOrDefault());
                                    monthlyData.data = data;
                                    restMonthlyData.Add(monthlyData);
                                    hc_new.monthly_data = restMonthlyData;
                                }
                                // In case that the entity didn't exist, it will be created in the database
                                if (hc_entity == null)
                                    await db.historicalClimatic.insertAsync(hc_new);
                                else
                                    await db.historicalClimatic.updateAsync(hc_entity, hc_new);
                            }
                        }
                    }
                    msg = new Message()
                    {
                        content = "Historical Climate WS. The file was imported correctly. Records imported: (" + (lines - 1).ToString() + ")  rows",
                        type = MessageType.successful
                    };
                    await writeEventAsync(msg.content, LogEvent.cre, new List<LogEntity>() { LogEntity.lc_weather_station, LogEntity.hs_historical_climatic });
                }
                else
                {
                    msg = new Message() { content = "Historical Climate WS. An error occurred with the file imported", type = MessageType.error };
                    await writeEventAsync(msg.content, LogEvent.err, new List<LogEntity>() { LogEntity.lc_weather_station });
                }
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                msg = new Message() { content = "Historical Climate WS. An error occurred in the system, contact the administrator", type = MessageType.error };
            }
            // List climate variables
            await generateListMeasuresAndSourceAsync();
            ViewBag.message = msg;
            return View("HistoricalClimate");
        }

        // GET: /Import/ImportClimatology
        [HttpGet]

Views/Import/Climatology.cshtml
@model CIAT.DAPA.USAID.Forecast.Data.Models.State
@using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Tools

@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    @if (ViewBag.message != null)
    {
        @if (ViewBag.message.type == MessageType.error)
        {
            <p class="bg-danger">@ViewBag.message.content</p>
        }
        else
        {
            <p class="bg-success">@ViewBag.message.content</p>
        }
    }
</div>
<fieldset>
    <legend>@Localizer["ClimatologyTitle"]</legend>
    <p class="text-justify">
        @Localizer["ClimatologyDescription"]
    </p>
    @using (Html.BeginForm("Climatology", "Import", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id)
        <div class="form-horizontal">
            <div class="form-group">
                <label class="control-label col-md-2" for="search">@Localizer["TypeSearch"]</label>
                <div class="col-md-10">
                    <label class="radio-inline">
                        <input type="radio" name="search" id="search" value="1" checked="checked">@Localizer["ExtID"]
                    </label>
                    <label class="radio-inline">
                        <input type="radio" name="search" id="search" value="2">@Localizer["Name"]
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="file">
                    @Localizer["ImportFile"]
                </label>
                <div class="col-md-10">
                    <input type="file" class="form-control" name="file" id="file" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="@Localizer["ImportCMD"]" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</fieldset>

Views/Import/HistoricalClimate.cshtml
@model CIAT.DAPA.USAID.Forecast.Data.Models.State
@using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Tools

@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    @if (ViewBag.message != null)
    {
        @if (ViewBag.message.type == MessageType.error)
        {
            <p class="bg-danger">@ViewBag.message.content</p>
        }
        else
        {
            <p class="bg-success">@ViewBag.message.content</p>
        }
    }
</div>
<fieldset>
    <legend>@Localizer["HistoricalTitle"]</legend>
    <p class="text-justify">
        @Localizer["HistoricalDescription"]
    </p>
    @using (Html.BeginForm("HistoricalClimate", "Import", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id)
        <div class="form-horizontal">
            <div class="form-group">
                <label class="control-label col-md-2" for="search">@Localizer["TypeSearch"]</label>
                <div class="col-md-10">
                    <label class="radio-inline">
                        <input type="radio" name="search" id="search" value="1" checked="checked">@Localizer["ExtID"]
                    </label>
                    <label class="radio-inline">
                        <input type="radio" name="search" id="search" value="2">@Localizer["Name"]
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="measures">@Localizer["Measure"]</label>
                <div class="col-md-10">
                    @Html.DropDownList("measures", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="file">
                    @Localizer["File"]
                </label>
                <div class="col-md-10">
                    <input type="file" class="form-control" name="file" id="file" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="@Localizer["ImportCMD"]" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</fieldset>

Views/Import/HistoricalYield.cshtml
@model CIAT.DAPA.USAID.Forecast.Data.Models.State
@using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Tools

@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    @if (ViewBag.message != null)
    {
        @if (ViewBag.message.type == MessageType.error)
        {
            <p class="bg-danger">@ViewBag.message.content</p>
        }
        else
        {
            <p class="bg-success">@ViewBag.message.content</p>
        }
    }
</div>
<fieldset>
    <legend>@Localizer["HistoricalTitle"]</legend>
    <p class="text-justify">
        @Localizer["HistoricalDescription"]
    </p>
    @using (Html.BeginForm("HistoricalYield", "Import", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id)
        <div class="form-horizontal">
            <div class="form-group">
                <div class="form-group">
                    <label class="control-label col-md-2" for="source">@Localizer["Source"]</label>
                    <div class="col-md-10">
                        @Html.DropDownList("source", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="file">
                    @Localizer["File"]
                </label>
                <div class="col-md-10">
                    <input type="file" class="form-control" name="file" id="file" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="@Localizer["ImportCMD"]" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</fieldset>