Controllers/SetupController.cs
using X.PagedList;
using CIAT.DAPA.USAID.Forecast.Data.Enums;
using CIAT.DAPA.USAID.Forecast.Data.Models;
using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Tools;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Linq;
using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Extend;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using Newtonsoft.Json;

namespace CIAT.DAPA.USAID.Forecast.WebAdmin.Controllers
{
    [Authorize(Roles = "ADMIN,IMPROVER")]
    [Authorize]
    public class SetupController : WebAdminBaseController
    {
        /// <summary>
        /// Method Construct
        /// </summary>
        /// <param name="settings">Settings options</param>
        /// <param name="hostingEnvironment">Host Enviroment</param>
        public SetupController(IOptions<Settings> settings, IHostingEnvironment hostingEnvironment,
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            RoleManager<Role> roleManager, IEmailSender emailSender) :
            base(settings, LogEntity.cp_setup, hostingEnvironment, userManager, signInManager, roleManager, emailSender)
        {
        }

        private async Task<PermissionList> LoadEnableByPermission(string countrySelected = "")
        {
            UserPermission permission = await getPermissionAsync();
            PermissionList val = new PermissionList();
            var countries = await db.country.listEnableAsync();
            val.countries = countries.Where(p => permission.countries.Contains(p.id)).ToList();
            val.states = await db.state.listEnableAsync();
            if (countrySelected != "" && countrySelected != "000000" && permission.countries.Count() > 1)
            {
                val.states = val.states.Where(p => permission.countries.Contains(p.country) && p.country == new MongoDB.Bson.ObjectId(countrySelected)).ToList();
            }
            else if (countrySelected == "" && permission.countries.Count() > 1)
            {
                val.states = val.states.Where(p => permission.countries.Contains(p.country) && p.country == permission.countries.FirstOrDefault()).ToList();
            }
            else
            {
                val.states = val.states.Where(p => permission.countries.Contains(p.country)).ToList();
            }


            var states_ids = val.states.Select(p => p.id).ToList();
            val.municipalities = await db.municipality.listEnableAsync();
            val.municipalities = val.municipalities.Where(p => states_ids.Contains(p.state)).ToList();
            var municipalities_ids = val.municipalities.Select(p => p.id).ToList();
            val.weather_stations = await db.weatherStation.listEnableAsync();
            val.weather_stations = val.weather_stations.Where(p => municipalities_ids.Contains(p.municipality)).ToList();

            var weather_station_ids = val.weather_stations.Select(p => p.id).ToList();
            val.setups = await db.setup.listEnableAsync();
            val.setups = val.setups.Where(p => weather_station_ids.Contains(p.weather_station)).ToList();
            return val;
        }

        // GET: SetupController
        [HttpGet]
        public async Task<IActionResult> Index(string sortOrder, int?page, string countrySelect = "")
        {
            try
            {
                ViewBag.CurrentSort = sortOrder;
                ViewBag.DatesortParam = sortOrder == "Date" ? "date_asc" : "Date";
                ViewBag.CropsortParam = sortOrder == "Crop" ? "crop_desc" : "Crop";
                ViewBag.WSsortParam = sortOrder == "WS" ? "ws_desc" : "WS";
                ViewBag.CultivarsortParam = sortOrder == "Cultivar" ? "cultivar_desc" : "Cultivar";
                ViewBag.SoilsortParam = sortOrder == "Soil" ? "soil_desc" : "Soil";
                ViewBag.DayssortParam = sortOrder == "Days" ? "days_desc" : "Days";
                //var setups = await db.setup.listEnableDescAsync();
                var data_with_permissions = await LoadEnableByPermission(countrySelect);
                var setups = data_with_permissions.setups;
                // Get the data
                var crp = await db.crop.listEnableAsync();
                var ws = await db.weatherStation.listEnableVisibleAsync();
                var cu = await db.cultivar.listEnableAsync();
                var so = await db.soil.listEnableAsync();
                List<SetupExtend> entities = new List<SetupExtend>();
                foreach (var s in setups)
                {
                    entities.Add(new SetupExtend(s, crp, ws, cu, so));
                }
                await writeEventAsync(setups.Count().ToString(), LogEvent.lis);
                switch (sortOrder) 
                {
                    case "date_asc":
                        entities = entities.OrderBy(p => p.track.register).ToList();
                        break;
                    case "Crop":
                        entities = entities.OrderBy(p => p.crop_name).ToList();
                        break;
                    case "crop_desc":
                        entities = entities.OrderByDescending(p => p.crop_name).ToList();
                        break;
                    case "WS":
                        entities = entities.OrderBy(p => p.weather_station_name).ToList();
                        break;
                    case "ws_desc":
                        entities = entities.OrderByDescending(p => p.weather_station_name).ToList();
                        break;
                    case "Cultivar":
                        entities = entities.OrderBy(p => p.cultivar_name).ToList();
                        break;
                    case "cultivar_desc":
                        entities = entities.OrderByDescending(p => p.cultivar_name).ToList();
                        break;
                    case "Soil":
                        entities = entities.OrderBy(p => p.soil_name).ToList();
                        break;
                    case "soil_desc":
                        entities = entities.OrderByDescending(p => p.soil_name).ToList();
                        break;
                    case "Days":
                        entities = entities.OrderBy(p => p.days).ToList();
                        break;
                    case "days_desc":
                        entities = entities.OrderByDescending(p => p.days).ToList();
                        break;
                    default:
                        Console.WriteLine(entities);
                        break;
                }
                var pageSize = 10;
                var pageNumber = (page ?? 1);

                if (countrySelect == "")
                {
                    ViewBag.countrySelected = data_with_permissions.countries[0].id.ToString();
                }
                else
                {
                    ViewBag.countrySelected = "";
                }
                ViewData["countriesData"] = getCountriesListWithDefult(data_with_permissions, countrySelect);

                return View(entities.ToPagedList(pageNumber, pageSize));
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return View();
            }
        }

        // GET: SetupController/Details/5
        public async Task<IActionResult> Details(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    await writeEventAsync("Search without id", LogEvent.err);
                    return new BadRequestResult();
                }
                Setup entity = await db.setup.byIdAsync(id);
                if (entity == null)
                {
                    await writeEventAsync("Not found id: " + id, LogEvent.err);
                    return new NotFoundResult();
                }
                await writeEventAsync("Search id: " + id, LogEvent.rea);
                var crp = await db.crop.listEnableAsync();
                var ws = await db.weatherStation.listEnableVisibleAsync();
                var cu = await db.cultivar.listEnableAsync();
                var so = await db.soil.listEnableAsync();

                ViewBag.crop_name = crp.SingleOrDefault(p => p.id == entity.crop).name;
                ViewBag.ws_name = ws.SingleOrDefault(p => p.id == entity.weather_station).name;
                ViewBag.cultivar_name = cu.SingleOrDefault(p => p.id == entity.cultivar).name;
                ViewBag.soil_name = so.SingleOrDefault(p => p.id == entity.soil).name;

                return View(entity);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return View();
            }
        }

        // GET: SetupController/Create
        public async Task<IActionResult> Create()
        {
            var setups = await db.setup.listEnableAsync();
            // Get the data
            var crp = await db.crop.listEnableAsync();
            var ws = await db.weatherStation.listEnableVisibleAsync();
            ViewBag.crop = new SelectList(crp, "id", "name");
            ViewBag.weather_station = new SelectList(ws, "id", "name");

            return View();
        }

        // POST: SetupController/Create
        [HttpPost, ActionName("CreateSetup")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Setup entity)
        {
            try
            {
                var form = HttpContext.Request.Form;
                entity.crop = getId(form["crop"]);
                entity.weather_station = getId(form["weather_station"]);
                entity.cultivar = getId(form["cultivar"]);

Views/Setup/Create.cshtml
@model CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Extend.SetupExtend

@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("CreateSetup", "Setup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <fieldset>
            <h4>@Localizer["Crop"]</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label for="crop" class="control-label col-md-2">@Localizer["Crop"]:</label>
                <div class="col-md-10">
                    @Html.DropDownList("crop", null, @Localizer["SelectCrop"].Value, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="weather_station" class="control-label col-md-2">@Localizer["WS"]:</label>
                <div class="col-md-10">
                    @Html.DropDownList("weather_station", null, @Localizer["SelectWS"].Value, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="cultivar" class="control-label col-md-2">@Localizer["Cultivar"]:</label>
                <div class="col-md-10">
                    @Html.DropDownList("cultivar", new SelectList(""), @Localizer["SelectCultivar"].Value, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="soil" class="control-label col-md-2">@Localizer["Soil"]:</label>
                <div class="col-md-10">
                    @Html.DropDownList("soil", new SelectList(""), @Localizer["SelectSoil"].Value, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="days" class="control-label col-md-2">@Localizer["Days"]:</label>
                <div class="col-md-10">
                    @Html.Editor("days", null, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>@Localizer["ConfFile"]</legend>
            <div class="form-group">
                <div class="col-md-">
                    <input type="button" id="add_file" value="@Localizer["AddFile"]" class="btn btn-default" />
                </div>
            </div>
            <table class="table" id="conf_files">
                <thead>
                    <tr>
                        <th>@Localizer["ParameterName"]</th>
                        <th>@Localizer["File"]</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </fieldset>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="@Localizer["Save"]" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(Localizer["Back"].Value, "Index")
</div>

@section Scripts {
    <script src="~/js/setup.js"></script>
}

Views/Setup/Delete.cshtml
@model CIAT.DAPA.USAID.Forecast.Data.Models.Setup

@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>@Localizer["Message"]</h3>
<div>
    <h4>@Localizer["Setup"]</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label class="control-label">
                @Localizer["ID"]
            </label>
        </dt>
        <dd>
            @Model.id.ToString()
        </dd>
        <dt>
            <label class="control-label">
                @Localizer["Crop"]
            </label>
        </dt>
        <dd>
            @ViewBag.crop_name
        </dd>
        <dt>
            <label class="control-label">
                @Localizer["Cultivar"]
            </label>
        </dt>
        <dd>
            @ViewBag.cultivar_name
        </dd>
        <dt>
            <label class="control-label">
                @Localizer["Soil"]
            </label>
        </dt>
        <dd>
            @ViewBag.soil_name
        </dd>
        <dt>
            <label class="control-label">
                @Localizer["WS"]
            </label>
        </dt>
        <dd>
            @ViewBag.ws_name
        </dd>
        <dt>
            <label class="control-label">
                @Localizer["RegisterDate"]
            </label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.track.register)
        </dd>
        <dt>
            <label class="control-label">
                @Localizer["UpdateDate"]
            </label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.track.updated)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id)

        <div class="form-actions no-color">
            <input type="submit" value="@Localizer["DeleteRecord"]" class="btn btn-default" /> |
            @Html.ActionLink(Localizer["Back"].Value, "Index")
        </div>
    }
</div>

Views/Setup/Details.cshtml
@model CIAT.DAPA.USAID.Forecast.Data.Models.Setup

@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>@Localizer["Setup"]</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label class="control-label">
                @Localizer["ID"]
            </label>
        </dt>
        <dd>
            @Model.id.ToString()
        </dd>
        <dt>
            <label class="control-label">
                @Localizer["Crop"]
            </label>
        </dt>
        <dd>
            @ViewBag.crop_name
        </dd>
        <dt>
            <label class="control-label">
                @Localizer["Cultivar"]
            </label>
        </dt>
        <dd>
            @ViewBag.cultivar_name
        </dd>
        <dt>
            <label class="control-label">
                @Localizer["Soil"]
            </label>
        </dt>
        <dd>
            @ViewBag.soil_name
        </dd>
        <dt>
            <label class="control-label">
                @Localizer["WS"]
            </label>
        </dt>
        <dd>
            @ViewBag.ws_name
        </dd>
        <dt>
            <label class="control-label">
                @Localizer["RegisterDate"]
            </label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.track.register)
        </dd>
        <dt>
            <label class="control-label">
                @Localizer["UpdateDate"]
            </label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.track.updated)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink(Localizer["Edit"].Value, "Edit", new { id = Model.id }) |
    @Html.ActionLink(Localizer["Back"].Value, "Index")
</p>

Views/Setup/Edit.cshtml
@model CIAT.DAPA.USAID.Forecast.Data.Models.Setup

@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("EditSetup", "Setup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <fieldset>
            <h4>@Localizer["Crop"]</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)
            <div class="form-group">
                <label for="crop" class="control-label col-md-2">@Localizer["Crop"]:</label>
                <div class="col-md-10">
                    @Html.DropDownList("crop", (SelectList)ViewData["crop"], @Localizer["SelectCrop"].Value, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="weather_station" class="control-label col-md-2">@Localizer["WS"]:</label>
                <div class="col-md-10">
                    @Html.DropDownList("weather_station", (SelectList)ViewData["ws"], @Localizer["SelectWS"].Value, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="cultivar" class="control-label col-md-2">@Localizer["Cultivar"]:</label>
                <div class="col-md-10">
                    @Html.DropDownList("cultivar", (SelectList)ViewData["cultivar"], @Localizer["SelectCultivar"].Value, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="soil" class="control-label col-md-2">@Localizer["Soil"]:</label>
                <div class="col-md-10">
                    @Html.DropDownList("soil", (SelectList)ViewData["soil"], @Localizer["SelectSoil"].Value, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="days" class="control-label col-md-2">@Localizer["Days"]:</label>
                <div class="col-md-10">
                    @Html.Editor("days", null, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>@Localizer["ConfFile"]</legend>
            <table class="table" id="edit_files">
                <thead>
                    <tr>
                        <th>@Localizer["File"]</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <ul>
                                @foreach (var item in Model.conf_files.Select((value, i) => new { i, value }))
                                {
                                <li>
                                    @Html.ActionLink(@item.value.name, "Download", "Home", new { file = @item.value.path.Split('\\').Last(), type = 1 }, new { target = "_blank" })
                                    <button type="button" id="delete_file_@item.i" value="" title="Delete file" class="btn btn-default" onclick="deleteFileConf(@item.i,'@Model.id')"><img class="img_delete_file" src="~/images/trash.png" /></button>
                                </li>
                                }
                            </ul>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <div class="col-md-">
                    <input type="button" id="add_file" value="@Localizer["AddFile"]" class="btn btn-default" />
                </div>
            </div>
            <table class="table" id="conf_files">
                <thead>
                    <tr>
                        <th>@Localizer["ParameterName"]</th>
                        <th>@Localizer["File"]</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </fieldset>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="@Localizer["Save"]" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(Localizer["Back"].Value, "Index")
</div>

@section Scripts {
    <script src="~/js/setup.js"></script>
    <link href="~/css/site.css" rel="stylesheet" type="text/css"/>
}

Views/Setup/Index.cshtml
@model X.PagedList.PagedList<CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Extend.SetupExtend>
@using X.PagedList.Mvc.Core
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink(Localizer["New"].Value, "Create")
</p>
<div style="display: flex;justify-content: start;gap: 8%;margin-bottom: 1%;">
    @{
        var countriesData = (SelectList)ViewData["countriesData"];
        var countryList = countriesData.ToList();
        string countrySelected = ViewBag.countrySelected;
    }
    @if (ViewBag.countrySelected != "")
    {
        @Html.Hidden("countrySelected", countrySelected)
    }
    @if (countryList.Count > 2)
    {
        <div class="col-md-4" style="display: flex;align-items: center;">
            @Html.Label("countrySelect", @Localizer["Filter"].Value, htmlAttributes: new { @class = "control-label col-md-2" })
            @using (Html.BeginForm("Index", "Setup", FormMethod.Get, htmlAttributes: new
            {
                @id = "selectForm",
                @style = "display: flex;align-items: center;gap: 2%;width: 80%;"
            }))
            {
                @Html.DropDownList("countrySelect", selectList: (SelectList)ViewData["countriesData"], optionLabel: null, htmlAttributes: new { @class = "form-control", onchange = "submitForm()" })
            }
        </div>
    }
    <input type="text" id="txt_search" class="form-control" onkeyup="search_text()" placeholder="@Localizer["Search"]" />
</div>
<h3>@Localizer["ConfAvalaible"]</h3>
<table class="table" id="index_list">
    <thead>
        <tr>
        <tr>
            <th>
                @Localizer["ID"]
            </th>
            <th>
                @Html.ActionLink(@Localizer["Date"].Value, "Index", new { sortOrder = ViewBag.DatesortParam })
            </th>
            <th>
                @Html.ActionLink(@Localizer["Crop"].Value, "Index", new { sortOrder = ViewBag.CropsortParam })
            </th>
            <th>
                @Html.ActionLink(@Localizer["WS"].Value, "Index", new { sortOrder = ViewBag.WSsortParam })
            </th>
            <th>
                @Html.ActionLink(@Localizer["Cultivar"].Value, "Index", new { sortOrder = ViewBag.CultivarsortParam })
            </th>
            <th>
                @Html.ActionLink(@Localizer["Soil"].Value, "Index", new { sortOrder = ViewBag.SoilsortParam })
            </th>
            <th>
                @Html.ActionLink(@Localizer["Days"].Value, "Index", new { sortOrder = ViewBag.DayssortParam })
            </th>
            <th>
                @Localizer["File"]
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Where(p => p.track.enable))
        {
            <tr>
                <td>
                    @item.id.ToString()
                </td>
                <td>
                    @item.track.register.ToString("yyyy-MM-dd")
                </td>
                <td>
                    @item.crop_name
                </td>
                <td>
                    @item.weather_station_name
                </td>
                <td>
                    @item.cultivar_name
                </td>
                <td>
                    @item.soil_name
                </td>
                <td>
                    @item.days
                </td>
                <td>
                    <ul>
                        @foreach (var f in item.conf_files)
                        {
                            <li>
                                @Html.ActionLink(f.name, "Download", "Home", new { file = @f.path.Split('/').Last(), type = 1 }, new { target = "_blank" })
                            </li>
                        }
                    </ul>
                </td>
                <td>
                    @Html.ActionLink(Localizer["Edit"].Value, "Edit", new { id = item.id }) |
                    @Html.ActionLink(Localizer["Details"].Value, "Details", new { id = item.id }) |
                    @Html.ActionLink(Localizer["Delete"].Value, "Delete", new { id = item.id })
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
@Localizer["Page"] @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) @Localizer["Of"] @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { sortOrder = ViewBag.CurrentSort, page }))

@section Scripts {
    @await Html.PartialAsync("_ManagementScriptsPartial")
}