Controllers/WeatherStationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CIAT.DAPA.USAID.Forecast.Data.Enums;
using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Tools;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Mvc;
using CIAT.DAPA.USAID.Forecast.Data.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Import;
using MongoDB.Bson;
using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Extend;
using CIAT.DAPA.USAID.Forecast.Data.Database;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;

namespace CIAT.DAPA.USAID.Forecast.WebAdmin.Controllers
{
    [Authorize(Roles = "ADMIN,CLIMATOLOGIST")]
    [Authorize]
    public class WeatherStationController : WebAdminBaseController
    {
        /// <summary>
        /// Method Construct
        /// </summary>
        /// <param name="settings">Settings options</param>
        /// <param name="hostingEnvironment">Host Enviroment</param>
        public WeatherStationController(IOptions<Settings> settings, IHostingEnvironment hostingEnvironment,
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            RoleManager<Role> roleManager, IEmailSender emailSender) : 
            base(settings, LogEntity.lc_weather_station, hostingEnvironment, userManager, signInManager, roleManager, emailSender)
        {
        }

        private async Task<PermissionList> LoadEnableByPermission()
        {
            UserPermission permission = await getPermissionAsync();
            PermissionList val = new PermissionList();
            var countries = await db.country.listEnableAsync();
            val.countries = countries.Where(p => permission.countries.Contains(p.id)).ToList();
            val.states = await db.state.listEnableAsync();
            val.states = val.states.Where(p => permission.countries.Contains(p.country)).ToList();
            var states_ids = val.states.Select(p => p.id).ToList();
            val.municipalities = await db.municipality.listEnableAsync();
            val.municipalities = val.municipalities.Where(p => states_ids.Contains(p.state)).ToList();
            var municipalities_ids = val.municipalities.Select(p => p.id).ToList();
            val.weather_stations = await db.weatherStation.listEnableAsync();
            val.weather_stations = val.weather_stations.Where(p => municipalities_ids.Contains(p.municipality)).ToList();
            return val;
        }

        private async Task<PermissionList> LoadAllByPermission(string countrySelected = "")
        {
            UserPermission permission = await getPermissionAsync();
            PermissionList val = new PermissionList();
            val.countries = await db.country.listAllAsync();
            val.countries = val.countries.Where(p => permission.countries.Contains(p.id)).ToList();
            val.states = await db.state.listAllAsync();
            if (countrySelected != "" && countrySelected != "000000" && permission.countries.Count() > 1)
            {
                val.states = val.states.Where(p => permission.countries.Contains(p.country) && p.country == new MongoDB.Bson.ObjectId(countrySelected)).ToList();
            }
            else if (countrySelected == "" && permission.countries.Count() > 1)
            {
                val.states = val.states.Where(p => permission.countries.Contains(p.country) && p.country == permission.countries.FirstOrDefault()).ToList();
            }
            else
            {
                val.states = val.states.Where(p => permission.countries.Contains(p.country)).ToList();
            }
            var states_ids = val.states.Select(p => p.id).ToList();
            val.municipalities = await db.municipality.listAllAsync();
            val.municipalities = val.municipalities.Where(p => states_ids.Contains(p.state)).ToList();
            var municipalities_ids = val.municipalities.Select(p => p.id).ToList();
            val.weather_stations = await db.weatherStation.listEnableAsync();
            val.weather_stations = val.weather_stations.Where(p => municipalities_ids.Contains(p.municipality)).ToList();
            return val;
        }

        // GET: /WeatherStation/
        [HttpGet]
        public async Task<IActionResult> Index(string countrySelect = "")
        {
            try
            {
                var obj = await LoadAllByPermission(countrySelect);
                var list = obj.weather_stations;
                ViewBag.municipalities = obj.municipalities;


                if (countrySelect == "")
                {
                    ViewBag.countrySelected = obj.countries[0].id.ToString();
                }
                else
                {
                    ViewBag.countrySelected = "";
                }
                ViewData["countriesData"] = getCountriesListWithDefult(obj, countrySelect);
                string dataJson = JsonConvert.SerializeObject(getListOfCountryStations(obj));
                ViewBag.data = dataJson;

                await writeEventAsync(list.Count().ToString(), LogEvent.lis);
                return View(list);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return View();
            }

        }

        // GET: /WeatherStation/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    await writeEventAsync("Search without id", LogEvent.err);
                    return new BadRequestResult();
                }
                WeatherStation entity = await db.weatherStation.byIdAsync(id);
                if (entity == null)
                {
                    await writeEventAsync("Not found id: " + id, LogEvent.err);
                    return new NotFoundResult();
                }
                await writeEventAsync("Search id: " + id, LogEvent.rea);
                return View(entity);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                return View();
            }
        }

        // GET: /WeatherStation/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await generateListMunicipalitiesAsync(string.Empty);
            return View();
        }

        // POST: /WeatherStation/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(WeatherStation entity)
        {
            try
            {
                entity.municipality = getId(HttpContext.Request.Form["municipality"].ToString());
                if (ModelState.IsValid)
                {
                    await db.weatherStation.insertAsync(entity);
                    await writeEventAsync(entity.ToString(), LogEvent.cre);
                    return RedirectToAction("Index");
                }
                await writeEventAsync(ModelState.ToString(), LogEvent.err);
                await generateListMunicipalitiesAsync(string.Empty);
                return View(entity);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                await generateListMunicipalitiesAsync(string.Empty);
                return View(entity);
            }
        }

        // GET: /WeatherStation/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            WeatherStation entity = null;
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    await writeEventAsync("Search without id", LogEvent.err);
                    return new BadRequestResult();
                }
                entity = await db.weatherStation.byIdAsync(id);
                if (entity == null)
                {
                    await writeEventAsync("Not found id: " + id, LogEvent.err);
                    return new NotFoundResult();
                }
                await writeEventAsync("Search id: " + id, LogEvent.rea);
                await generateListAllMunicipalitiesAsync(entity.municipality.ToString());
                return View(entity);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                await generateListAllMunicipalitiesAsync(entity.municipality.ToString());
                return View(entity);
            }
        }

        // POST: /WeatherStation/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(WeatherStation entity, string id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    WeatherStation current_entity = await db.weatherStation.byIdAsync(id);

                    entity.id = getId(id);
                    entity.municipality = getId(HttpContext.Request.Form["municipality"].ToString());
                    await db.weatherStation.updateAsync(current_entity, entity);
                    await writeEventAsync(entity.ToString(), LogEvent.upd);
                    return RedirectToAction("Index");
                }
                await writeEventAsync(ModelState.ToString(), LogEvent.err);
                await generateListAllMunicipalitiesAsync(entity.municipality.ToString());
                return View(entity);
            }
            catch (Exception ex)
            {
                await writeExceptionAsync(ex);
                await generateListAllMunicipalitiesAsync(entity.municipality.ToString());
                return View(entity);
            }
        }

        // GET: /WeatherStation/Delete/5
        [HttpGet]

Views/WeatherStation/Configuration.cshtml
@model IEnumerable<CIAT.DAPA.USAID.Forecast.Data.Models.ConfigurationFile>
@using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Tools

@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h4>@ViewBag.ws_name</h4>

@if (ViewBag.message != null)
{
    @if (ViewBag.message.type == MessageType.error)
    {
        <p class="bg-danger">@ViewBag.message.content</p>
    }
    else
    {
        <p class="bg-success">@ViewBag.message.content</p>
    }
}

@using (Html.BeginForm("Configuration", "WeatherStation", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <input type="hidden" id="id" name="id" value="@ViewBag.ws_id" />
    <div class="form-horizontal">
        <fieldset>
            <legend>@Localizer["ConfFile"]</legend>
            <div class="form-group">
                <label for="name" class="control-label col-md-2">@Localizer["ConfFileName"]:</label>
                <div class="col-md-10">
                    @Html.Editor("name", null, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                <label for="label" class="control-label col-md-2">@Localizer["ConfFileFile"]:</label>
                <div class="col-md-10">
                    <input class="form-control" id="file" name="file" type="file"  />
                </div>
            </div>            
        </fieldset>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="@Localizer["ConfFileSave"]" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink(Localizer["Back"].Value, "Details", new { id = ViewBag.ws_id })
</div>
<h3>@Localizer["ConfFileAvalaible"]</h3>
<table class="table">
    <tr>
        <th>@Localizer["ConfFileName"]</th>
        <th>@Localizer["Date"]</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.name, "Download", "Home", new { file = item.path.Split('/').Last(), type = 1 }, new { target = "_blank" })                
            </td>
            <td>
                @item.date
            </td>
        </tr>
    }
</table>
<div>
    @Html.ActionLink(Localizer["Back"].Value, "Details", new { id = ViewBag.ws_id })
</div>

@section Scripts {

}

Views/WeatherStation/Create.cshtml
@model CIAT.DAPA.USAID.Forecast.Data.Models.WeatherStation

@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Localizer["WS"]</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.municipality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.municipality, selectList: (SelectList)ViewData["municipality"], optionLabel: null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.municipality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.origin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.origin, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.origin, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ext_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ext_id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ext_id, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.visible, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.visible, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.visible, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.latitude, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.latitude, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.longitude, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.longitude, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.elevation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.elevation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.elevation, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Localizer["Save"]" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(Localizer["Back"].Value, "Index")
</div>

Views/WeatherStation/Delete.cshtml
@model CIAT.DAPA.USAID.Forecast.Data.Models.WeatherStation

@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>@Localizer["Message"]</h3>
<div>
    <h4>@Localizer["WS"]</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.municipality)
        </dt>

        <dd>
            @Model.municipality.ToString()
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.origin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.origin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ext_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ext_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.visible)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.visible)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.latitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.elevation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.elevation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.track.register)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.track.register)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.track.updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.track.updated)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id)

        <div class="form-actions no-color">
            <input type="submit" value="@Localizer["DeleteRecord"]" class="btn btn-default" /> |
            @Html.ActionLink(Localizer["Back"].Value, "Index")
        </div>
    }
</div>

Views/WeatherStation/Details.cshtml
@model CIAT.DAPA.USAID.Forecast.Data.Models.WeatherStation

@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>@Localizer["WS"]</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.municipality)
        </dt>

        <dd>
            @Model.municipality.ToString()
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.origin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.origin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ext_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ext_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.visible)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.visible)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.latitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.elevation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.elevation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.track.register)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.track.register)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.track.updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.track.updated)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(Localizer["Edit"].Value, "Edit", new { id = Model.id }) |
    @Html.ActionLink(Localizer["Ranges"].Value, "Range", new { id = Model.id }) |
    @Html.ActionLink(Localizer["Setup"].Value, "Configuration", new { id = Model.id }) |
    @Html.ActionLink(Localizer["Back"].Value, "Index")
</p>

Views/WeatherStation/Index.cshtml
@using CIAT.DAPA.USAID.Forecast.Data.Models
@using System.Linq
@using Newtonsoft.Json
@model IEnumerable<CIAT.DAPA.USAID.Forecast.Data.Models.WeatherStation>
@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink(Localizer["New"].Value, "Create")
</p>

<div style="display: flex;justify-content: start;gap: 8%;margin-bottom: 1%;">
    @{
        var countriesData = (SelectList)ViewData["countriesData"];
        var countryList = countriesData.ToList();
        string countrySelected = ViewBag.countrySelected;
    }
    @if (ViewBag.countrySelected != "")
    {
        @Html.Hidden("countrySelected", countrySelected)
    }
    @if (countryList.Count > 2)
    {
        <div class="col-md-4" style="display: flex;align-items: center;">
            @Html.Label("countrySelect", @Localizer["Filter"].Value, htmlAttributes: new { @class = "control-label col-md-2" })
            @using (Html.BeginForm("Index", "WeatherStation", FormMethod.Get, htmlAttributes: new
            {
                @id = "selectForm",
                @style = "display: flex;align-items: center;gap: 2%;width: 80%;"
            }))
            {
                @Html.DropDownList("countrySelect", selectList: (SelectList)ViewData["countriesData"], optionLabel: null, htmlAttributes: new { @class = "form-control", onchange = "submitForm()" })
            }
        </div>
    }
    <input type="text" id="txt_search" class="form-control" onkeyup="search_text()" placeholder="@Localizer["Search"]" />
</div>
<table class="table" id="index_list">
    <tr>
        <th>
            @Localizer["Municipality"]
        </th>
        <th>
            @Localizer["ID"]
        </th>
        <th>
            @Localizer["Name"]
        </th>
        <th>
            @Localizer["Origin"]
        </th>
        <th>
            @Localizer["Ext_ID"]
        </th>
        <th>
            @Localizer["Visible"]
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{ var m = ((List<Municipality>)ViewBag.municipalities).FirstOrDefault(p => p.id == item.municipality); }
                @m.name
            </td>
            <td>
                @item.id.ToString()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.origin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ext_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.visible)
            </td>
            <td>
                @Html.ActionLink(Localizer["Edit"].Value, "Edit", new { id = item.id }) |
                @Html.ActionLink(Localizer["Details"].Value, "Details", new { id = item.id }) |
                @Html.ActionLink(Localizer["Ranges"].Value, "Range", new { id = item.id }) |
                @Html.ActionLink(Localizer["Setup"].Value, "Configuration", new { id = item.id }) |
                @Html.ActionLink(Localizer["Delete"].Value, "Delete", new { id = item.id })
            </td>
        </tr>
    }
</table>

@section Scripts {
    @await Html.PartialAsync("_ManagementScriptsPartial")
}

Views/WeatherStation/Range.cshtml
@model IEnumerable<CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Extend.CropYieldRange>
@using CIAT.DAPA.USAID.Forecast.WebAdmin.Models.Tools

@{
    ViewBag.Title = Localizer["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h4>@ViewBag.ws_name</h4>

@if (ViewBag.message != null)
{
    @if (ViewBag.message.type == MessageType.error)
    {
        <p class="bg-danger">@ViewBag.message.content</p>
    }
    else
    {
        <p class="bg-success">@ViewBag.message.content</p>
    }
}

@using (Html.BeginForm("Range", "WeatherStation", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <input type="hidden" id="id" name="id" value="@ViewBag.ws_id" />
    <div class="form-horizontal">
        <fieldset>
            <legend>@Localizer["Title"]</legend>
            <div class="form-group">
                <label for="weather_station" class="control-label col-md-2">@Localizer["Crop"]:</label>
                <div class="col-md-10">
                    @Html.DropDownList("crop", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="label" class="control-label col-md-2">@Localizer["Description"]:</label>
                <div class="col-md-10">
                    @Html.Editor("label", null, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                <label for="lower" class="control-label col-md-2">@Localizer["LimitLower"]:</label>
                <div class="col-md-10">
                    @Html.Editor("lower", null, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                <label for="upper" class="control-label col-md-2">@Localizer["LimitUpper"]:</label>
                <div class="col-md-10">
                    @Html.Editor("upper", null, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </fieldset>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="@Localizer["Save"]" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink(Localizer["Back"].Value, "Details", new { id = ViewBag.ws_id })
</div>
<h3>@Localizer["RangesCrop"]</h3>
<table class="table">
    <tr>
        <th>@Localizer["Crop"]</th>
        <th>@Localizer["Description"]</th>
        <th>@Localizer["LimitLower"]</th>
        <th>@Localizer["LimitUpper"]</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.crop_name
            </td>
            <td>
                @item.label
            </td>
            <td>
                @item.lower
            </td>
            <td>
                @item.upper
            </td>
            <td>
                @using (Html.BeginForm("RangeDelete", "WeatherStation", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="ws" name="ws" value="@ViewBag.ws_id" />
                    <input type="hidden" id="crop" name="crop" value="@item.crop" />                    
                    <input type="hidden" id="label" name="label" value="@item.label" />
                    <input type="hidden" id="lower" name="lower" value="@item.lower.ToString()" />
                    <input type="hidden" id="upper" name="upper" value="@item.upper.ToString()" />
                    <input class="btn btn-danger" type="submit" value="@Localizer["Delete"]" />
                }
            </td>
        </tr>
    }
</table>
<div>
    @Html.ActionLink(Localizer["Back"].Value, "Details", new { id = ViewBag.ws_id })
</div>

@section Scripts {
    
}